version: '2'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
       - pgadmindata:/var/lib/pgadmin
       - ./pgadmin:/var/lib/pgadmin/storage/postgres
    ports:
      - "80:80"
    links:
      - postgres:postgres
    restart: unless-stopped

volumes:
  dbdata: # this named docker volume store the database data
  pgadmindata: # this named docker volume store the pgadmin data
